#!/usr/bin/env bash
#
# OpenObserve rum-events-format upstream sync.
#
# Rebuilds the OpenObserve `openobserve` branch from a pristine upstream
# (DataDog/rum-events-format) commit:
#
#   1. checks out the upstream commit on a new sync branch
#   2. restores fork-owned files from the openobserve branch (keep-ours.txt)
#   3. runs the rebrand codemod (rename-map.json): _dd -> _o2, propagator enum, identity
#   4. regenerates lib/generated/** from the rebranded schemas (`yarn generate`)
#   5. formats and records the new upstream base
#
# Unlike the browser-sdk sync, this repo has no functional patch series: every
# fork change is expressible as a codemod rule, and the generated types are
# rebuilt from the rebranded schemas rather than hand-edited.
#
# Usage:
#   scripts/openobserve/sync-upstream.sh [<commit-ish>]
#
#   <commit-ish>   Upstream commit/ref to sync to (e.g. a full SHA or upstream/master).
#                  When omitted, the tip of the upstream default branch is used.
#   UPSTREAM_REMOTE (default: upstream), BASE_BRANCH (default: openobserve)
#   SKIP_GENERATE=1  Skip `yarn install`/`yarn generate`/`yarn format` (rebrand only).
#
# Exit codes: 0 success (or already up to date), 1 usage/precondition error.
set -euo pipefail

UPSTREAM_REMOTE=${UPSTREAM_REMOTE:-upstream}
BASE_BRANCH=${BASE_BRANCH:-openobserve}
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

if [ -n "$(git status --porcelain -uno)" ]; then
  echo "error: working tree has uncommitted changes to tracked files" >&2
  exit 1
fi

git fetch "$UPSTREAM_REMOTE" --prune --quiet
git fetch origin "$BASE_BRANCH" --quiet 2>/dev/null || true

# The tooling lives on the openobserve branch, but the working tree is about to become the
# upstream commit. Work from a temp copy so the script and its data files survive the checkout.
TOOLING=$(mktemp -d)
trap 'rm -rf "$TOOLING"' EXIT
git show "$BASE_BRANCH:scripts/openobserve/rebrand.mjs" > "$TOOLING/rebrand.mjs"
git show "$BASE_BRANCH:scripts/openobserve/rename-map.json" > "$TOOLING/rename-map.json"
git show "$BASE_BRANCH:scripts/openobserve/keep-ours.txt" > "$TOOLING/keep-ours.txt"
CURRENT_BASE=$(git show "$BASE_BRANCH:scripts/openobserve/UPSTREAM_BASE" 2>/dev/null || echo 'none')

# ---- Resolve the target commit ----------------------------------------------
TARGET_REF=${1:-"$UPSTREAM_REMOTE/HEAD"}
if ! TARGET=$(git rev-parse --verify "${TARGET_REF}^{commit}" 2>/dev/null); then
  # Fall back to the remote's default branch tip if HEAD symref is unset.
  TARGET=$(git rev-parse --verify "${UPSTREAM_REMOTE}/master^{commit}")
fi
SHORT=$(git rev-parse --short "$TARGET")

if [ "$TARGET" = "$CURRENT_BASE" ]; then
  echo "Already up to date with upstream $SHORT."
  exit 0
fi

echo "Syncing upstream ${CURRENT_BASE:0:12} -> $TARGET"
# The sync branch descends from the openobserve branch (so the PR merges cleanly and its
# diff shows exactly what changes), but its tree is replaced with the upstream commit content.
SYNC_BRANCH="sync/upstream-$SHORT"
git checkout -B "$SYNC_BRANCH" "$BASE_BRANCH"
git rm -rfq . >/dev/null
git checkout "$TARGET" -- .
git clean -fd --quiet

# ---- Keep-ours overlay -------------------------------------------------------
# Fork-owned paths are taken from the openobserve branch. Directories are replaced
# wholesale so files deleted on the openobserve branch do not resurrect.
grep -vE '^\s*(#|$)' "$TOOLING/keep-ours.txt" | while read -r p; do
  if git cat-file -e "$BASE_BRANCH:$p" 2>/dev/null; then
    rm -rf "$p"
    git checkout "$BASE_BRANCH" -- "$p"
  else
    echo "keep-ours: '$p' not found on $BASE_BRANCH, skipping"
  fi
done

# ---- Rebrand codemod ----------------------------------------------------------
node "$TOOLING/rebrand.mjs"

# ---- Regenerate types from the rebranded schemas ------------------------------
if [ "${SKIP_GENERATE:-0}" != "1" ]; then
  corepack enable >/dev/null 2>&1 || true
  yarn install --no-immutable
  yarn generate
  yarn build
  yarn format --write || npx prettier@2.7.1 --write . || true
fi

echo "$TARGET" > scripts/openobserve/UPSTREAM_BASE

# Apache-2.0 §4 attribution gate: fail the sync if Datadog attribution was erased.
node scripts/openobserve/check-attribution.mjs

git add -A
git commit --quiet -m "chore(sync): rebrand upstream rum-events-format @$SHORT as OpenObserve

Generated by scripts/openobserve/sync-upstream.sh:
- upstream commit: $TARGET
- keep-ours overlay from $BASE_BRANCH
- rebrand codemod (scripts/openobserve/rename-map.json): _dd -> _o2, +openobserve propagator
- lib/generated rebuilt from rebranded schemas (yarn generate)"

echo
echo "Sync branch $SYNC_BRANCH is ready (upstream $SHORT)."
echo "Review, run 'yarn validate', push, and open a PR against $BASE_BRANCH."
echo "Then update the browser-sdk pin: yarn openobserve:schemas --update $(git rev-parse HEAD)"
